### ISSUE TITLE
Azure Key Vault Env Injector - unable to create pod

### ISSUE THREAD

**Issue by geoffchalk** [SparebankenVest/public-helm-charts#1]
I have kubernetes cluster in AZURE on VM's ( so, bare metal k8s).
I have installed Azure Key Vault Env Injector and controller, the controller does create the kubernetes secret with correct values, BUT env injector fails to create the pod.
here are the configs 

mypod.yaml
```bash
apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: mypod
spec:
  containers:
  - image: nginx:1.15.5
    name: mypod
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi
    env:
    - name: MY_SECRET
      value: my-azure-keyvault-secret@azurekeyvault
```

my-azure-keyvault-secret.yaml
```bash
# my-azure-keyvault-secret.yaml
apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  name: "my-azure-keyvault-secret"
  namespace: mypod
spec:
  vault:
    name: "my-key-vault-01"
    object:
      type: secret
      name: "my-secret"
  output: # ignored by env injector, required by controller to output kubernetes secret
    secret:
      name: meera-adf-01-secret
      dataKey: MY_SERCRET
```

I get he following errors:
```bash
Error from server (InternalError): error when creating "mypod.yaml": Internal error occurred: failed calling admission webhook "pods.azure-key-vault-env-injector.admission.spv.no": an error on the server ("{\"response\":{\"uid\":\"b77082c2-7336-11e9-a6e4-000d3a3a2463\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"Secret \\\"\\\" is invalid: metadata.name: Required value: name or generateName is required\"}}}") has prevented the request from succeeding
```

I get this from the injector logs:
```bash
time="2019-05-10T15:07:48Z" level=info msg="docker image docker.io/library/nginx:1.15.5 pulled successfully"
time="2019-05-10T15:07:48Z" level=info msg="inspecting container image docker.io/library/nginx:1.15.5, looking for entrypoint and cmd"
time="2019-05-10T15:07:48Z" level=info msg="using cmd from image: [nginx -g daemon off;]"
time="2019-05-10T15:07:48Z" level=info msg="using cmd from image: [nginx -g daemon off;]"
time="2019-05-10T15:07:48Z" level=info msg="using 'nginx -g daemon off; nginx -g daemon off;' as arguments for env-injector"
time="2019-05-10T15:07:48Z" level=info msg="creating secret in new namespace 'mypod'..."
2019/05/10 15:07:48 [ERROR] admission webhook error: Secret "" is invalid: metadata.name: Required value: name or generateName is required
```

**Comment by torresdal** [comment]
Hi @geoffchalk,

Are you using default auth or are you overriding authentication (https://github.com/SparebankenVest/azure-key-vault-to-kubernetes/blob/master/README.md#override-default-authentication)?

**Comment by torresdal** [comment]
...also @geoffchalk : Could you post the actual output in Kubernetes for the Azure Key Vault Secret?

E.g: `kubectl -n mypod get my-azure-keyvault-secret -o yaml`

**Comment by geoffchalk** [comment]
key vault secret from kubectl is
```apiVersion: spv.no/v1alpha1
kind: AzureKeyVaultSecret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"spv.no/v1alpha1","kind":"AzureKeyVaultSecret","metadata":{"annotations":{},"name":"my-azure-keyvault-secret","namespace":"test"},"spec":{"output":{"secret":{"dataKey":"REDIS_PASSWORD","name":"meera-adf-01-secret"}},"vault":{"name":"meera-01","object":{"name":"redis-password","type":"secret"}}}}
  creationTimestamp: 2019-05-13T10:55:18Z
  generation: 1
  name: my-azure-keyvault-secret
  namespace: test
  resourceVersion: "38564672"
  selfLink: /apis/spv.no/v1alpha1/namespaces/test/azurekeyvaultsecrets/my-azure-keyvault-secret
  uid: 98bfa414-756d-11e9-a6e4-000d3a3a2463
spec:
  output:
    secret:
      dataKey: REDIS_PASSWORD
      name: meera-adf-01-secret
  vault:
    name: meera-01
    object:
      name: redis-password
      type: secret
status:
  lastAzureUpdate: 2019-05-13T13:55:03Z
  secretHash: fcd593045a21f79dc878a2c5472dd8f1
  secretName: meera-adf-01-secret```

**Comment by geoffchalk** [comment]
the helm installation for both controller and injector:
## key-vault-env-injector deployment
```
helm install --name  env-injector --namespace default spv-charts/azure-key-vault-env-injector   --set customAuth.enabled=true   --set customAuth.autoInject.enabled=true  --set env.AZURE_TENANT_ID="..........."  --set env.AZURE_CLIENT_ID="..........." --set env.AZURE_CLIENT_SECRET="........." --set env.AZURE_TENANT_ID="..........."
```
## key-vault-contoller deployment
```
helm install --name  key-vault-controller --namespace default spv-charts/azure-key-vault-controller  --set keyVault.customAuth.enabled=true --set env.AZURE_TENANT_ID="......"  --set env.AZURE_CLIENT_ID=".........." --set env.AZURE_CLIENT_SECRET=".........." --set env.AZURE_TENANT_ID=".........." --set installCrd=false
```

**Comment by geoffchalk** [comment]
also the /etc/kubernetes/azure.json has the same credentials.
I have managed to get the key vault secret into a kubernetes secret, buut we require the env injector

**Comment by geoffchalk** [comment]
Here is the error i get from trying to deploy the mypod.yaml from earlier
```
kubectl apply -f mypod.yaml 
Error from server (InternalError): error when creating "mypod.yaml": Internal error occurred: failed calling admission webhook "pods.azure-key-vault-env-injector.admission.spv.no": an error on the server ("{\"response\":{\"uid\":\"d54fe648-7589-11e9-a6e4-000d3a3a2463\",\"allowed\":false,\"status\":{\"metadata\":{},\"status\":\"Failure\",\"message\":\"Secret \\\"\\\" is invalid: metadata.name: Required value: name or generateName is required\"}}}") has prevented the request from succeeding
```

**Comment by vidarw** [comment]
@geoffchalk Have you tried initializing the env-injector without custom authentication? Will spend some time to try to recreate your scenario in our test environment.

Another top of mind suggestion: Could you try to also set customAuth.autoInject.secretName and see if that secret populates correctly based on your input? Not sure if that one is mandatory :/

**Comment by geoffchalk** [comment]
Vidar,

I have tried without custom authentication, but this did not work, also I tried customAuth.autoInject.secretName but setting this fails the install with this error
“Error: release env-injector failed: Deployment.apps "env-injector-azure-key-vault-env-injector" is invalid: spec.template.spec.containers[0].env[6].name: Required value”

Regards,
Geoff

Geoff Chalk

[signature_837765390]

T: +44 (0) 1483 762816
E: g<mailto:geoff.chalk@target-energysolutions.com>eoff.chalk@target-energysolutions.com<mailto:geoff.chalk@target-energysolutions.com>
W: www.target-energysolutions.com<http://www.target-energysolutions.com/>

**Comment by geoffchalk** [comment]
Vidar,
Also helm install without custom auth fails the Azure Key Vault Controller install with the following in the controller logs:
time="2019-05-13T16:24:48Z" level=info msg="Log level set to 'info'"
time="2019-05-13T16:24:48Z" level=info msg="Creating event broadcaster"
time="2019-05-13T16:24:48Z" level=fatal msg="failed to create azure key vault credentials, error: Unmarshall error: yaml: line 2: did not find expected ',' or '}'"


Geoff Chalk

[signature_1457047649]

T: +44 (0) 1483 762816
E: g<mailto:geoff.chalk@target-energysolutions.com>eoff.chalk@target-energysolutions.com<mailto:geoff.chalk@target-energysolutions.com>
W: www.target-energysolutions.com<http://www.target-energysolutions.com/>

**Comment by nagarjunb-auxolabs** [comment]
I'm trying to create a key-vault-env-injector.
Which application's Tenant Id, Client Id and Client Secret Id has to be sent in "key-vault-env-injector" installation command.

**Comment by eimarfandino** [comment]
i had the same issue and i tried without custom authentication as well and got a different error:
```Error creating: Internal error occurred: failed calling webhook "pods.azure-key-vault-env-injector.admission.spv.no": Post https://sandbox-efandino-azure-keyvault-env-injector-azure-key-vault-en.sandbox-efandino.svc:443/pods?timeout=30s: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "svc-cat-ca")```

**Comment by torresdal** [comment]
We will have to take a closer look at custom auth, as there seams to be several issues. Meantime please provide any updates or discoveries you have. Will report back as soon as we have any updates. Thanks.

**Comment by torresdal** [comment]
Custom auth or not - quite sure this is because env-injector is installed in a namespace with `azure-key-vault-env-injection: enabled` - as documentet under **Env injector - failed calling webhook** at https://akv2k8s.io/known-issues

Install all akv2k8s components into its own namespace and this should not happen.
