### ISSUE TITLE
Env Injector installation fails if customAuth.autoInject.secretName is set

### ISSUE THREAD

**Issue by carpppa** [SparebankenVest/public-helm-charts#10]
Hi,

Env Injector helm installation fails, if `customAuth.autoInject.secretName` parameter is set.

In `stable/azure-key-vault-env-injector/templates/deployment.yaml`, line [66 and 67](https://github.com/SparebankenVest/public-helm-charts/blob/master/stable/azure-key-vault-env-injector/templates/deployment.yaml#L66), in `env` block, the YAML keys are written in capitals (i.e., as `NAME` and `VALUE` instead of `name` and `value`). As a consequence, the install fails with error:

`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(Deployment.spec.template.spec.containers[0].env[6]): unknown field "NAME" in io.k8s.api.core.v1.EnvVar, ValidationError(Deployment.spec.template.spec.containers[0].env[6]): unknown field "VALUE" in io.k8s.api.core.v1.EnvVar, ValidationError(Deployment.spec.template.spec.containers[0].env[6]): missing required field "name" in io.k8s.api.core.v1.EnvVar]`

The problem can be reproduced with the example in the [readme](https://github.com/SparebankenVest/public-helm-charts/tree/master/stable/azure-key-vault-env-injector#using-custom-authentication-with-credential-injection-enabled) (using Helm 3.0.2):

```
helm install \
  --set customAuth.enabled=true \
  --set customAuth.autoInject.enabled=true \
  --set customAuth.autoInject.secretName=azure-key-vault-secret \
  --set env.AZURE_TENANT_ID=foo \
  --set env.AZURE_CLIENT_ID=bar \
  --set env.AZURE_CLIENT_SECRET=baz \
  test spv-charts/azure-key-vault-env-injector
```

Specifically, setting `customAuth.autoInject.secretName` produces the issue. Dropping this parameter produces the problem discussed in issue #1 (`[ERROR] admission webhook error: Secret "" is invalid: metadata.name: Required value: name or generateName is required`).

The linked pull request fixes the problem.

**Comment by torresdal** [comment]
This should now be fixed when pr #11 is merged.
