### ISSUE TITLE
Probing to controller fails for version 2.3.4/5 in AKS 1.25.5

### ISSUE THREAD

**Issue by SireMartin** [SparebankenVest/public-helm-charts#105]
I am using AKS version 1.25.5 and after deploying the latest version of akv2k8s (2.3.5) the probing fails for the controller. The envinjector does respond to probing.

Warning  Unhealthy  2m3s (x10 over 2m51s)  kubelet            Readiness probe failed: Get "http://10.240.25.5:9000/healthz": dial tcp 10.240.25.5:9000: connect: connection refused
  Warning  Unhealthy  113s (x6 over 2m43s)   kubelet            Liveness probe failed: Get "http://10.240.25.5:9000/healthz": dial tcp 10.240.25.5:9000: connect: connection refused
  Normal   Killing    113s (x2 over 2m23s)   kubelet            Container controller failed liveness probe, will be restarted

When i revert to version 2.3.2 the problem is solved. 

Reverting to 2.3.4 does not solve the problem, however other clusters on k8s version 1.25.5 are running version 2.3.4 (installed on May 23th as the latest version) without having this problem. When i updated on of those to the actual version 2.3.4, the problem occurs.

**Comment by PassionateDeveloper86** [comment]
Same here!

**Comment by johncclayton** [comment]
Seeing the same thing on an AKS cluster @ 1.26.3, when I revert to 2.3.2 the problem (/healthz) goes away.

**Comment by johanra** [comment]
I encountered the same issue, seems that liveness & readiness probes were added to the controller in commit c9c47aaf9505534d122c96e0d81b91d79d0837da by @LennartTimmers 
Problem is that the health endpoint is only available when metrics are enabled, so probably these probes should only be added when metrics are enabled.

a workaround is to enable metrics in values.yaml
values:
    global:
      metrics:
        enabled: true

**Comment by SireMartin** [comment]
Thanks @johanra this works!

**Comment by karpediemnow** [comment]
Same here:

reverting to 2.3.5 does not solve the issue
