### ISSUE TITLE
Azure credentials stored in env section of deployment in plain text

### ISSUE THREAD

**Issue by yix** [SparebankenVest/public-helm-charts#12]
Both azure-key-vault-controller and azure-key-vault-env-injector currently store Azure credentials (specifically AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET) in env section of the deployment in plain text which is highly insecure and can be viewed by those who are not allowed to view secrets in the cluster.

```
        - name: AZURE_CLIENT_ID
          value: 00000000-0000-0000-0000-000000000000
        - name: AZURE_CLIENT_SECRET
          value: 00000000-0000-0000-0000-000000000000
        - name: AZURE_TENANT_ID
          value: 00000000-0000-0000-0000-000000000000

**Comment by torresdal** [comment]
Thanks for this! Your pull request is now merged.
