### ISSUE TITLE
No PodDisruptionBudget defined allowing pod to become unavailable 

### ISSUE THREAD

**Issue by Aaron-ML** [SparebankenVest/public-helm-charts#15]
Without a PDB defined a cluster event such as cluster upgrades could create a window where the pod(s) aren't available creating an outage. 

Ideally with a ReplicaCount greater than 1 you'd set a PDB to allow 1/50% disruptions so the upgrade can be successful without impacting the service availability 

I'll see if I can get a PR in shortly.

**Comment by torresdal** [comment]
Totally agree. Thanks. Looking at the pr now.
