### ISSUE TITLE
Using in AKS without RBAC

### ISSUE THREAD

**Issue by gilgamezh** [SparebankenVest/public-helm-charts#2]
Hello! is it possible to use it without rbac? my aks cluster is created with `enableRbac: false`

I tried to install with helm and I'm getting this error

```
 ~/code/pyar_infra   master  helm install spv-charts/azure-key-vault-controller \                                                                                                                                                      3ms 
  --set installCrd=false
Error: release joyous-billygoat failed: clusterroles.rbac.authorization.k8s.io "joyous-billygoat-azure-key-vault-controller" is forbidden: attempt to grant extra privileges: [{[get] [spv.no] [azurekeyvaultsecrets] [] []} {[list] [spv.no] [azurekeyvaultsecrets] [] []} {[watch] [spv.no] [azurekeyvaultsecrets] [] []} {[update] [spv.no] [azurekeyvaultsecrets] [] []} {[patch] [spv.no] [azurekeyvaultsecrets/status] [] []} {[update] [spv.no] [azurekeyvaultsecrets/status] [] []} {[create] [] [secrets] [] []} {[update] [] [secrets] [] []} {[delete] [] [secrets] [] []} {[get] [] [secrets] [] []} {[watch] [] [secrets] [] []} {[list] [] [secrets] [] []} {[create] [] [events] [] []} {[update] [] [events] [] []} {[patch] [] [events] [] []}] user=&{system:serviceaccount:kube-system:default d4c50c2d-a48f-11e8-919f-d6836346c66b [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] map[]} ownerrules=[] ruleResolutionErrors=[clusterroles.rbac.authorization.k8s.io "system:discovery" not found]
```

**Comment by torresdal** [comment]
Probably not. Honestly we haven’t tried.

The least thing we can do is update the docs to reflect the fact.

Is it important for you to have it work in a cluster without rbac or were you just happening to test with that cluster?

We CAN add support for it, but I honestly can’t see why anyone would run a cluster without rbac. Please let us know if this is something we should support and why.

**Comment by gilgamezh** [comment]
thanks four your reply! I wanted to try it. 

If you want to point me on how to support it maybe I can try and send a PR

Meanwhile I'm going to deploy a new cluster with rbac.

**Comment by torresdal** [comment]
@gilgamezh we don't really want to support it :-) So unless you have a really good reason for needing it, my recommendation is to use a cluster with rbac.

**Comment by torresdal** [comment]
Closing this for new. Please reopen if working without rbac is important.
