### ISSUE TITLE
Wrong if statment in chart

### ISSUE THREAD

**Issue by marchenm** [SparebankenVest/public-helm-charts#23]
https://github.com/SparebankenVest/public-helm-charts/blob/b18c9dad4413c44a9aa310b8573684cad32ec466/stable/akv2k8s/templates/controller-deployment.yaml#L62

that should be either `if .Values.runningInsideAzureAks` or `if not .Values.controller.customAuth.enabled`

**Comment by torresdal** [comment]
@marchenm fixed. Actually values.yaml was wrong as well. Corrected to:

```
{{- if not .Values.controller.keyVault.customAuth.enabled }}
```
