### ISSUE TITLE
Pod labels should be moved to the template

### ISSUE THREAD

**Issue by marchenm** [SparebankenVest/public-helm-charts#24]
https://github.com/SparebankenVest/public-helm-charts/blob/b18c9dad4413c44a9aa310b8573684cad32ec466/stable/azure-key-vault-controller/templates/deployment.yaml#L20-L22

Line 20-22 should be moved to be between line 27 & 28. 

In its current state the chart doesn't output valid yaml when specifying `podLabels`.

**Comment by torresdal** [comment]
@marchenm fixed
