### ISSUE TITLE
Controller/env injector run as root

### ISSUE THREAD

**Issue by tschuettel** [SparebankenVest/public-helm-charts#25]
Hi,

your Azure Key Vault integration is a really nice tool which I have been looking for a while. 

Today, I realized that the processes inside your docker containers run as root which is not allowed in our Azure Policy.
Is there any way to get the containers to run as non-root?

Thanks a lot.
Tom

**Comment by torresdal** [comment]
It depends on what type of autentication you're using. If default, the container needs to run as root in order to access azure cloud config, as described here: https://akv2k8s.io/security/authentication/#situations-where-default-authentication-does-not-work

**Comment by tschuettel** [comment]
Thanks for the quick response.
It's true for the default config because the pod needs to be able to read a file which is only accessible by the root user.

However,  I managed to get the pod running as non-root when using customAuth. In this case you also not mounting /etc/kubernetes/azure.json.
Would it be possible to also add a securityContext section to the deployment, if customAuth=true?

In this case the pod can run as 'nobody' user:
```
...
{{- if not .Values.controller.keyVault.customAuth.enabled }}
securityContext:
  runAsUser: 65534
  fsGroup: 65534
{{- end }}
```

**Comment by tschuettel** [comment]
Sorry for the late reply.

My AKS is setup using managed identities (--enable-managed-identity). To get AKV2K8S running with customAuth, I had to specify the client id of the "<cluster_name>-agentpool" identity to the chart:
```
helm upgrade -i akv2k8s spv-charts/akv2k8s \
          --namespace akv2k8s \
          --set controller.keyVault.customAuth.enabled=true \
          --set controller.env.AZURE_CLIENT_ID={{.AKS_USER_MANAGED_IDENTITY}} \
          --set env_injector.enabled=false 
```

**Comment by archittsc** [comment]
> Sorry for the late reply.
> 
> My AKS is setup using managed identities (--enable-managed-identity). To get AKV2K8S running with customAuth, I had to specify the client id of the "<cluster_name>-agentpool" identity to the chart:
> 
> ```
> helm upgrade -i akv2k8s spv-charts/akv2k8s \
>           --namespace akv2k8s \
>           --set controller.keyVault.customAuth.enabled=true \
>           --set controller.env.AZURE_CLIENT_ID={{.AKS_USER_MANAGED_IDENTITY}} \
>           --set env_injector.enabled=false 
> ```

@tschuettel do you have any idea know how can we achieve this using the values in helm charts? I am struggling to get the pods up as non root, after adding my MSI details. I am getting the error - 
"failed to create cloud config provider for azure key vault" err="Failed reading azure config from /etc/kubernetes/azure.json, error: failed reading cloud config, error: read /etc/kubernetes/azure.json: is a directory" file="/etc/kubernetes/azure.json"

I can see that cloudConfig is defined as "/etc/kubernetes/azure.json" in the values.yaml and its being picked up as an argument for the container. Now as the container is trying to start as non root it is obvious the path - /etc/kubernetes/azure.json won't be accessible by it, so how do I mitigate this? Am i missing something here?
