### ISSUE TITLE
hostPath type check failed: /etc/kubernetes/azure.json is not a file

### ISSUE THREAD

**Issue by maximefifen** [SparebankenVest/public-helm-charts#27]
i try to deploy azure keyvault controller on rancher, i follow this step:

1-
kubectl apply -f https://raw.githubusercontent.com/sparebankenvest/azure-key-vault-to-kubernetes/master/crds/AzureKeyVaultSecret.yaml --namespace=akv2k8s

2-
helm repo add spv-charts http://charts.spvapi.no

3-
helm update

4-
helm upgrade -i akv2k8s spv-charts/akv2k8s --namespace akv2k8s --set keyVault.customAuth.enabled=true --set env.AZURE_TENANT_ID= --set env.AZURE_CLIENT_ID= --set env.AZURE_CLIENT_SECRET=

5-
the deployment finish well

but i also have the issue with azure-config:

MountVolume.SetUp failed for volume "azure-config" : hostPath type check failed: /etc/kubernetes/azure.json is not a file

**Comment by torresdal** [comment]
These --set values are not valid for this chart. Please re-check the chart README.

**Comment by maximefifen** [comment]
Now it's work
i use this PR https://github.com/SparebankenVest/public-helm-charts/pull/17
