### ISSUE TITLE
Deprecation of azure-key-vault-crd will block Terraform deployments

### ISSUE THREAD

**Issue by pedrohdz** [SparebankenVest/public-helm-charts#29]
Hey!
We use Terraform quite heavily at our organization, we spin up complex environments with a single command.  Deprecating `azure-key-vault-crd` would force use to stop deployments halfway to execute `kubectl apply` then continue our deployments.  Other alternatives without something like `azure-key-vault-crd` would be very hacky.

Why not continue with [Method 2: Separate Charts](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you) as described in the Helm documentation?  The `kubectl apply` approach could still be available as an alternative.

Thanks!

**Comment by 181192** [comment]
Hello @pedrohdz,

The new [akv2k8s helm 3 chart](https://github.com/SparebankenVest/public-helm-charts/tree/master/stable/akv2k8s) have the CRD's included, use this instead :blush:

**Comment by pedrohdz** [comment]
Woohoo!  Thanks!  :-)
