### ISSUE TITLE
admission.spv

### ISSUE THREAD

**Issue by AndreRochaDev** [SparebankenVest/public-helm-charts#3]

**Comment by AndreRochaDev** [comment]
Hey! When I am creating a pod, I get this error, any ideas of why this is happening?
Error creating: Internal error occurred: failed calling webhook "pods.azure-key-vault-env-injector.admission.spv.no": an error on the server has prevented the request from succeeding

**Comment by AndreRochaDev** [comment]
I discovered what the problem is, I need to pass an imagepullsecret to the injector it seems, it is unable to pull the image on the admission webhook  because it is unauthorized, is it configurable? I dont find that configuration on the table, maybe I can help with this

**Comment by torresdal** [comment]
This related to custom auth, which we will have to revisit as there seam to be some issues. Ref issue #1

**Comment by torresdal** [comment]
Closing this for now and will follow up on issue #1 which covers the same issue.
