### ISSUE TITLE
Wrong service name when upgrade --install helm 3 chart akv2k8s

### ISSUE THREAD

**Issue by kvitaly2005** [SparebankenVest/public-helm-charts#32]
Hello,

I tried to install new HELM chart and have injector not working due to:

Internal error occurred: failed calling webhook
        "pods.azure-key-vault-env-injector.admission.spv.no": Post
        https://akv2k8s-azure-key-vault-env-injector.akv2k8s.svc:443/pods?timeout=30s:
        service "akv2k8s-azure-key-vault-env-injector" not found

This is not issue with labeling, I walked thru the guide step by step.

There is no akv2k8s-azure-key-vault-env-injector service because it is created as "akv2k8s-envinjector"

I did not found any hard coded string "azure-key-vault-env-injector" as well as service parameter name and assume it is from old chart. I tried to reinstall chart from scratch, but still get wrong name. 

Why it is wrong and where can I specify the service name (apart from rename it manually)?

kind: Service
apiVersion: v1
metadata:
  name: akv2k8s-envinjector
  namespace: akv2k8s
  selfLink: /api/v1/namespaces/akv2k8s/services/akv2k8s-envinjector
  uid: 8e756267-9f63-4a76-b37e-e9c26962b596
  resourceVersion: '15739570'
  creationTimestamp: '2020-11-25T16:46:56Z'
  labels:
    app.kubernetes.io/instance: akv2k8s
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: env-injector
    helm.sh/chart: akv2k8s-1.1.26

**Comment by 181192** [comment]
Hello @kvitaly2005, if this is still an issue you should check the `MutatingWebhookConfiguration`'s in your cluster and see if there's any duplicates from older charts.

I'm closing this issue for now, feel free to reach out for any further questions or reopen the issue with more details :blush:
