### ISSUE TITLE
AzurePodIdentityException installs into wrong namespace

### ISSUE THREAD

**Issue by pinkfloydx33** [SparebankenVest/public-helm-charts#47]
When using `--set addAzurePodIdentityException=true` installation of the chart fails if you are installing into a namespace other than `akv2k8s`. The template for the `AzurePodIdentityException` is hardcoded to install into the `akv2k8s` namespace. 

https://github.com/SparebankenVest/public-helm-charts/blob/d0cdc16570505d4b1c99b0ff44c7a4f3afdddacc/stable/akv2k8s/templates/controller-azure-pod-identity-exception.yaml#L6

We're working around the fact that we install into a different namespace by setting to `false` and adding the `AzurePodIdentityException` manually, but it would be nice for the chart to install it properly.

**Comment by 181192** [comment]
Thanks @pinkfloydx33, fixed in chart version 2.0.9 :blush:

**Comment by pinkfloydx33** [comment]
Thanks for quick response!
