### ISSUE TITLE
Couldn't install injector

### ISSUE THREAD

**Issue by nagarjunb-auxolabs** [SparebankenVest/public-helm-charts#5]
Sample query : helm install spv-charts/azure-key-vault-env-injector --namespace **** --name kvi --set customAuth.autoInject.enabled=true --set customAuth.enabled=true -
-set customAuth.autoInject.secretName=azure-key-vault-secret --set env.AZURE_TENANT_ID=********-****-****-****-************ --set env.AZURE_CLIENT_ID=********-****-****-****-c8cb
********** --set env.AZURE_CLIENT_SECRET=*************

Error: release kvi failed: Deployment.apps "kvi-azure-key-vault-env-injector" is invalid: spec.template.spec.containers[0].env[6].name: Required value

In the sample query, passed all the required values, still getting the error on containers[0].env[6].name as required value

Kindly help

**Comment by torresdal** [comment]
There are reported issues with custom auth that needs to be fixed. Will follow up in issue #1 - closing this as duplicate.
