### ISSUE TITLE
New AKV2K8S helm 3 chart values.yaml is missing the runningInsideAzureAks field in values.yaml

### ISSUE THREAD

**Issue by tspearconquest** [SparebankenVest/public-helm-charts#54]
The link below references an environment variable which is blank upon deploying the chart
This was set to true in the helm 2 chart and appears to be needed here as well.

https://github.com/SparebankenVest/public-helm-charts/blob/471366ad84302865cbdc066c138b4f8cf0fdb0e6/stable/akv2k8s/templates/env-injector-deployment.yaml#L69-L70

**Comment by 181192** [comment]
Hi @tspearconquest!

`RUNNING_INSIDE_AZURE_AKS` env was removed in akv2k8s 1.2 release in favor of using `AUTH_TYPE` env  / `.Values.global.keyVaultAuth` chart value. :relaxed:
