### ISSUE TITLE
Helm Upgrade fail on AKS

### ISSUE THREAD

**Issue by jasonlasater** [SparebankenVest/public-helm-charts#75]
On AKS v 1.19.11, akv2k8s helm upgrade from 2.1.0 to 2.2.0 fails as follows:

Error: unable to build kubernetes objects from release manifest: unable to recognize "":  no matches for kind "PodDisruptionBudget" in version "policy/v1"

Uninstall and fresh installation with updated repo appears to produce the same error.

**Comment by 181192** [comment]
Fixed in #74 released in chart version 2.2.1
