### ISSUE TITLE
Chart forces azure.json even when using custom auth

### ISSUE THREAD

**Issue by jdfalk** [SparebankenVest/public-helm-charts#8]
The chart forces the mount of /etc/kubernetes/azure.json despite using custom auth. When using custom auth that whole section should be removed or another option should be added to disable it. I will create a PR with a separate option.

**Comment by MystiqueRose** [comment]
> The chart forces the mount of /etc/kubernetes/azure.json despite using custom auth. When using custom auth that whole section should be removed or another option should be added to disable it. I will create a PR with a separate option.

I'm having the same issue using a GKE cluster.

**Comment by torresdal** [comment]
Did PR #17 fix this issue for you? Please reopen if not.
