### ISSUE TITLE
Error when adding controller labels in akv2k8s chart

### ISSUE THREAD

**Issue by EmceeMichaelC** [SparebankenVest/public-helm-charts#88]
When adding labels to `controller.labels` in the values file, I get the following error installing the chart:
```
Error: YAML parse error on akv2k8s/templates/controller-deployment.yaml: error converting YAML to JSON: yaml: line 10: mapping values are not allowed in this context
```
I believe using `nindent` instead of `indent` on the following line should fix this issue.

https://github.com/SparebankenVest/public-helm-charts/blob/master/stable/akv2k8s/templates/controller-deployment.yaml#L13

**Comment by 181192** [comment]
Thank you @EmceeMichaelC fixed :relieved:
