### ISSUE TITLE
Env Injector does not have Pod Annotations support

### ISSUE THREAD

**Issue by ok-night** [SparebankenVest/public-helm-charts#96]
Env Injector deployment does not have Pod Annotations support like the Controller deployment has. We would like to add annotations for these as well in our organisation.

The change is very simple and I have it prepared but I seem to not have rights to push to this repo to create a PR.

```
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/env-injector-apiservice.yaml") . | sha256sum }}
        {{- if .Values.env_injector.podAnnotations }}
        {{ toYaml .Values.env_injector.podAnnotations | nindent 8 }}
        {{- end }}
```
And corresponding inputs to values.yaml:
```
  # -- Additional pods labels
  podLabels: {}

  # -- Additional pod annotations
  podAnnotations: {}

```

Could someone help me? :)

**Comment by 181192** [comment]
Thanks @ok-night, added in chart version 2.3.4 :relaxed:
